defaults: &defaults
  country: Argentina
  gmaps_url: "http://maps.googleapis.com/maps/api/js?key=AIzaSyBuaeRl4SDBP2M3QNhtwhMFGnKkfX6nIyk&sensor=true&v=3.7&libraries=geometry"
  jquery_url: "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"

  bus_icon_path: "public/buses_images/:id.png"
  bus_icons_path: "public/buses_images/"
  buses_sprite_path: "public/buses_images.png"
  build_buses_sprite_on_demand: true
  facebook_page_url: https://www.facebook.com/pages/MapaDeColectivosMarDelPlata/211856755596258


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  authorized_domains:
    - blooming-stream-4501.herokuapp.com
    - mapadecolectivosmdp.com.ar
